#cmakedefine AC_APPLE_UNIVERSAL_BUILD				1
#cmakedefine HAVE_CTYPE_H								1
#cmakedefine HAVE_DIRENT_H								1
#cmakedefine HAVE_DLFCN_H								1
#cmakedefine HAVE_FCNTL_H								1
#cmakedefine HAVE_GCC_ATOMIC_OPS					1
#cmakedefine HAVE_GETENV								1
#cmakedefine HAVE_GETPAGESIZE							1
#cmakedefine HAVE_ICONV									1
#cmakedefine HAVE_INTTYPES_H							1
#cmakedefine HAVE_IO_H									1
#cmakedefine HAVE_LIBPTHREAD							1
#cmakedefine HAVE_MEMORY_H							1
#cmakedefine HAVE_MMAP									1
#cmakedefine HAVE_OPENDIR								1
#cmakedefine HAVE_OSX_ATOMIC_OPS					1
#cmakedefine HAVE_PTHREAD_H							1
#cmakedefine HAVE_STDINT_H								1
#cmakedefine HAVE_STDLIB_H								1
#cmakedefine HAVE_STRINGS_H							1
#cmakedefine HAVE_STRING_H								1
#cmakedefine HAVE_SYS_MMAN_H						1
#cmakedefine HAVE_SYS_PARAM_H						1
#cmakedefine HAVE_SYS_STAT_H							1
#cmakedefine HAVE_SYS_TIMES_H							1
#cmakedefine HAVE_SYS_TYPES_H							1
#cmakedefine HAVE_TLS_KEYWORD						1
#cmakedefine HAVE_UNISTD_H								1
#define HAVE_UNSIGNED_LONG_LONG_INT				1
#cmakedefine HAVE_WINDOWS_H							1